# Generated by Django 5.1.2 on 2026-06-02 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CodeSnippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python")], default="python", max_length=20
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("fork_count", models.IntegerField(default=0)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="compiler.codesnippet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="code_snippets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "code_snippets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "code_snippet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_likes",
                        to="compiler.codesnippet",
                    ),
                ),
            ],
            options={
                "db_table": "code_likes",
            },
        ),
        migrations.CreateModel(
            name="ExecutionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("output", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("running", "Running"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("execution_time", models.FloatField(default=0)),
                ("memory_used", models.FloatField(default=0)),
                ("stdin", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "code_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executions",
                        to="compiler.codesnippet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "execution_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="codesnippet",
            index=models.Index(
                fields=["user", "-created_at"], name="code_snippe_user_id_a5a902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="codesnippet",
            index=models.Index(
                fields=["is_public", "-likes"], name="code_snippe_is_publ_e1a717_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="codelike",
            unique_together={("user", "code_snippet")},
        ),
        migrations.AddIndex(
            model_name="executionhistory",
            index=models.Index(
                fields=["user", "-created_at"], name="execution_h_user_id_e2b120_idx"
            ),
        ),
    ]
