# Generated by Django 6.0.6 on 2026-06-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0002_ai_query_cache"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiquery",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="aiquerycache",
            options={"ordering": ["-last_hit"]},
        ),
        migrations.RenameIndex(
            model_name="aiquery",
            new_name="ai_queries_user_id_088f53_idx",
            old_name="compiler_aiquery_user_created_idx",
        ),
        migrations.RenameIndex(
            model_name="aiquery",
            new_name="ai_queries_query_h_c5377a_idx",
            old_name="compiler_aiquery_hash_idx",
        ),
        migrations.RenameIndex(
            model_name="aiquery",
            new_name="ai_queries_action_dd3dcb_idx",
            old_name="compiler_aiquery_action_status_idx",
        ),
        migrations.RenameIndex(
            model_name="aiquery",
            new_name="ai_queries_provide_c3c593_idx",
            old_name="compiler_aiquery_provider_idx",
        ),
        migrations.AlterField(
            model_name="codesnippet",
            name="language",
            field=models.CharField(
                choices=[("python", "Python"), ("c", "C"), ("cpp", "C++")],
                default="python",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerycache",
            index=models.Index(
                fields=["query_hash"], name="ai_query_ca_query_h_4a6185_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerycache",
            index=models.Index(fields=["action"], name="ai_query_ca_action_f06769_idx"),
        ),
        migrations.AddIndex(
            model_name="aiquerycache",
            index=models.Index(
                fields=["last_hit"], name="ai_query_ca_last_hi_70229d_idx"
            ),
        ),
    ]
