# Generated by Django 6.0.6 on 2026-06-08 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0003_alter_aiquery_options_alter_aiquerycache_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[("python", "Python"), ("c", "C"), ("cpp", "C++")],
                        default="python",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                            ("stopped", "Stopped"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "execution_time",
                    models.FloatField(
                        default=0, help_text="Total execution time in seconds"
                    ),
                ),
                (
                    "total_lines",
                    models.IntegerField(default=0, help_text="Total output lines"),
                ),
                (
                    "error_lines",
                    models.IntegerField(default=0, help_text="Number of error lines"),
                ),
                ("return_code", models.IntegerField(default=0)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional execution metadata",
                    ),
                ),
                (
                    "code_snippet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminal_executions",
                        to="compiler.codesnippet",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminal_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "terminal_executions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="TerminalExecutionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("output", "Standard Output"),
                            ("error", "Error Output"),
                            ("input", "User Input"),
                            ("step", "Execution Step Marker"),
                            ("status", "Status Update"),
                            ("summary", "Execution Summary"),
                        ],
                        default="output",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="The actual output/error text")),
                (
                    "line_number",
                    models.IntegerField(help_text="Line number in terminal output"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_time_at_step",
                    models.FloatField(
                        default=0,
                        help_text="Total execution time when this step was generated",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Step-specific metadata (error_type, status, etc)",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="compiler.terminalexecution",
                    ),
                ),
            ],
            options={
                "db_table": "terminal_execution_steps",
                "ordering": ["line_number"],
            },
        ),
        migrations.CreateModel(
            name="TerminalInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "input_number",
                    models.IntegerField(
                        help_text="Order of input (1st, 2nd, 3rd input, etc)"
                    ),
                ),
                ("content", models.TextField(help_text="The user-provided input")),
                ("provided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_time_at_input",
                    models.FloatField(
                        help_text="Total execution time when input was provided"
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(
                        blank=True,
                        help_text="The prompt text the program showed before requesting input",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="compiler.terminalexecution",
                    ),
                ),
            ],
            options={
                "db_table": "terminal_inputs",
                "ordering": ["input_number"],
            },
        ),
        migrations.AddIndex(
            model_name="terminalexecution",
            index=models.Index(
                fields=["user", "-started_at"], name="terminal_ex_user_id_9d3ea6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="terminalexecution",
            index=models.Index(fields=["status"], name="terminal_ex_status_999ac1_idx"),
        ),
        migrations.AddIndex(
            model_name="terminalexecutionstep",
            index=models.Index(
                fields=["execution", "line_number"],
                name="terminal_ex_executi_550795_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="terminalexecutionstep",
            index=models.Index(
                fields=["step_type"], name="terminal_ex_step_ty_0bcaa6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="terminalinput",
            unique_together={("execution", "input_number")},
        ),
    ]
