# Generated by Django 5.1.2 on 2026-06-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_adminlog_useractivity_usersatisfaction_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="code_quality_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_language",
            field=models.CharField(blank=True, default="python", max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="login_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_ai_tokens_used",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_code_executions",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_session_time",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="total_snippets_created",
            field=models.IntegerField(default=0),
        ),
    ]
