# Generated by Django 5.1.2 on 2026-06-06 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_userprofile_email_verified_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("compile", "Code Compilation"),
                    ("snippet_create", "Snippet Created"),
                    ("snippet_view", "Snippet Viewed"),
                    ("project_create", "Project Created"),
                    ("project_edit", "Project Edited"),
                    ("community_post", "Community Post"),
                    ("community_like", "Community Like"),
                    ("community_comment", "Community Comment"),
                    ("ai_chat", "AI Chat Usage"),
                    ("format_code", "Code Format"),
                    ("analyze_code", "Code Analysis"),
                    ("email_verified", "Email Verified"),
                    ("password_reset", "Password Reset"),
                    ("page_view", "Page View"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("page", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_heartbeats",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="user_heartb_user_id_e52933_idx",
                    )
                ],
            },
        ),
    ]
