# Generated by Django 6.0.6 on 2026-06-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="useractivity",
            name="user_activity_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="activity_timestamp_idx",
        ),
        migrations.RemoveIndex(
            model_name="userheartbeat",
            name="user_heartbeat_idx",
        ),
        migrations.RemoveIndex(
            model_name="userheartbeat",
            name="heartbeat_timestamp_idx",
        ),
        migrations.RemoveIndex(
            model_name="userprofile",
            name="email_verified_idx",
        ),
        migrations.RemoveIndex(
            model_name="usersession",
            name="user_session_idx",
        ),
    ]
