# Generated by Django 6.0.6 on 2026-06-10 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_useractivity_user_activity_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(
                fields=["user", "-created_at"], name="email_verif_user_id_10ad9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailverificationtoken",
            index=models.Index(fields=["token"], name="email_verif_token_df7c5e_idx"),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(
                fields=["user", "-created_at"], name="password_re_user_id_fcb0eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="passwordresettoken",
            index=models.Index(fields=["token"], name="password_re_token_060a1f_idx"),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["user", "-timestamp"], name="user_activi_user_id_6bb195_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivity",
            index=models.Index(
                fields=["activity_type", "-timestamp"],
                name="user_activi_activit_b512c7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersatisfaction",
            index=models.Index(
                fields=["user", "-submitted_at"], name="user_satisf_user_id_69383f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersatisfaction",
            index=models.Index(fields=["rating"], name="user_satisf_rating_70d5d9_idx"),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "-login_time"], name="user_sessio_user_id_d40ce8_idx"
            ),
        ),
    ]
