# Generated by Django 5.1.2 on 2026-06-03 21:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        default="code",
                        help_text="FontAwesome icon class",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Problem Categories",
                "db_table": "problem_categories",
            },
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "description",
                    models.TextField(help_text="Problem description with examples"),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Detailed explanation of the problem"
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (1, "Easy"),
                            (2, "Medium"),
                            (3, "Hard"),
                            (4, "Expert"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "time_limit",
                    models.FloatField(
                        default=1.0,
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "memory_limit",
                    models.IntegerField(
                        default=256,
                        validators=[django.core.validators.MinValueValidator(64)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("submissions", models.IntegerField(default=0)),
                ("accepted_submissions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="problems",
                        to="problems.problemcategory",
                    ),
                ),
            ],
            options={
                "db_table": "problems",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.IntegerField(help_text="Duration in minutes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("max_participants", models.IntegerField(blank=True, null=True)),
                ("participants", models.IntegerField(default=0)),
                ("submissions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_contests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "problems",
                    models.ManyToManyField(
                        related_name="contests", to="problems.problem"
                    ),
                ),
            ],
            options={
                "db_table": "contests",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ProblemAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_solved", models.BooleanField(default=False)),
                ("first_solved_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("best_execution_time", models.FloatField(blank=True, null=True)),
                ("best_memory_used", models.FloatField(blank=True, null=True)),
                ("first_attempt_at", models.DateTimeField(auto_now_add=True)),
                ("last_attempt_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_attempts",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_attempts",
            },
        ),
        migrations.CreateModel(
            name="ProblemRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="1-5 star rating",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "difficulty_rating",
                    models.IntegerField(
                        default=0,
                        help_text="User's perception of difficulty (optional)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_ratings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProblemSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(default="python", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("accepted", "Accepted"),
                            ("wrong_answer", "Wrong Answer"),
                            ("runtime_error", "Runtime Error"),
                            ("timeout", "Time Limit Exceeded"),
                            ("memory_limit", "Memory Limit Exceeded"),
                            ("compilation_error", "Compilation Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("passed_tests", models.IntegerField(default=0)),
                ("total_tests", models.IntegerField(default=0)),
                (
                    "execution_time",
                    models.FloatField(default=0, help_text="Execution time in seconds"),
                ),
                (
                    "memory_used",
                    models.FloatField(default=0, help_text="Memory used in MB"),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "failed_test_case",
                    models.IntegerField(
                        blank=True, help_text="Index of first failed test", null=True
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("judged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_submissions",
                        to="problems.problem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_data", models.TextField(help_text="Input for the problem")),
                ("expected_output", models.TextField(help_text="Expected output")),
                (
                    "is_sample",
                    models.BooleanField(
                        default=False, help_text="Show in problem description"
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, help_text="Used for final judging"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Explanation for sample test case"
                    ),
                ),
                ("order", models.IntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problems.problem",
                    ),
                ),
            ],
            options={
                "db_table": "test_cases",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProblemStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problems_solved", models.IntegerField(default=0)),
                ("problems_attempted", models.IntegerField(default=0)),
                ("total_submissions", models.IntegerField(default=0)),
                ("total_accepted", models.IntegerField(default=0)),
                ("easy_solved", models.IntegerField(default=0)),
                ("medium_solved", models.IntegerField(default=0)),
                ("hard_solved", models.IntegerField(default=0)),
                ("expert_solved", models.IntegerField(default=0)),
                ("best_acceptance_rate", models.FloatField(default=0)),
                (
                    "average_solve_time",
                    models.FloatField(default=0, help_text="Average time in minutes"),
                ),
                ("longest_streak", models.IntegerField(default=0, help_text="Days")),
                ("current_streak", models.IntegerField(default=0, help_text="Days")),
                ("last_solved", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_problem_stats",
            },
        ),
        migrations.CreateModel(
            name="ContestParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problems_solved", models.IntegerField(default=0)),
                ("total_score", models.IntegerField(default=0)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "penalty_time",
                    models.IntegerField(default=0, help_text="Penalty in minutes"),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="problems.contest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contest_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contest_participations",
                "ordering": ["rank", "total_score"],
                "unique_together": {("user", "contest")},
            },
        ),
        migrations.AddIndex(
            model_name="contest",
            index=models.Index(
                fields=["status", "start_time"], name="contests_status_d2169e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemattempt",
            index=models.Index(
                fields=["user", "is_solved"], name="problem_att_user_id_677391_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="problemattempt",
            unique_together={("user", "problem")},
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["status", "-created_at"], name="problems_status_457a2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(
                fields=["difficulty", "category"], name="problems_difficu_0acf41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["-views"], name="problems_views_23aaca_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="problemrating",
            unique_together={("user", "problem")},
        ),
        migrations.AddIndex(
            model_name="problemsubmission",
            index=models.Index(
                fields=["user", "problem", "-submitted_at"],
                name="problem_sub_user_id_af0cdc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="problemsubmission",
            index=models.Index(
                fields=["problem", "status"], name="problem_sub_problem_2dbebd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="problemsubmission",
            index=models.Index(
                fields=["-submitted_at"], name="problem_sub_submitt_7fd158_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcase",
            index=models.Index(
                fields=["problem", "is_sample"], name="test_cases_problem_ad5bcc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcase",
            unique_together={("problem", "order")},
        ),
    ]
