# Generated by Django 6.0.6 on 2026-07-02 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_postlike"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["category", "-created_at"],
                name="community_p_categor_a0275d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="communitypost",
            index=models.Index(
                fields=["user", "-created_at"], name="community_p_user_id_73cd49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="postcomment",
            index=models.Index(
                fields=["post", "-created_at"], name="post_commen_post_id_4c6246_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["follower"], name="user_follow_followe_a0b992_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userfollow",
            index=models.Index(
                fields=["following"], name="user_follow_followi_eaf074_idx"
            ),
        ),
    ]
